name: Validate Renovate Config

on:
  pull_request: {}
  push:
    branches:
      - renovate/reconfigure

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:41.144.2@sha256:a6a97cc5ad9884c7c390e8db99fe4e80d2daf96a8bc4a08d052d1b0f2a12c423
      options: --user root
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: renovate --version
      - run: renovate-config-validator .github/renovate.json5
