name: Validate Renovate Config

on:
  pull_request: {}
  push:
    branches:
      - renovate/reconfigure

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:44.58.0@sha256:20fe6c849d43c6ea039a66bd56eacb9fd48862a43145673230daaf963bbdad7d
      options: --user root
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: renovate --version
      - run: renovate-config-validator .github/renovate.json5
