name: Validate Renovate Config

on:
  pull_request: {}
  push:
    branches:
      - renovate/reconfigure

permissions:
  contents: read

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate:41.97.8@sha256:6cd1144718eb4d012a534d42f3a1019f8f7ece2cd9c5283270eaa1491d1af7de
      options: --user root
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: renovate --version
      - run: renovate-config-validator .github/renovate.json5
